### ISSUE TITLE
Using default host variable results in "Can't modify frozen array" error

### ISSUE THREAD

**Issue by roback** [twingly/twingly-amqp#53]
I tried to use the `QueuePublisher` (not just related to the `QueuePublisher` though) in a test in wally but got the following message. The reason is that I used the default host variable, which is now frozen since https://github.com/twingly/twingly-amqp/commit/22acd31ccd2263351a1dd8df5067ebdc8b3fba3f#diff-a37f3e6add223b058bddda335dda3b17R10 (❤️  RuboCop). Everything works when using a `RABBITMQ_01_HOST` env variable, since the array isn't frozen then.

The line in bunny that causes the problem: https://github.com/ruby-amqp/bunny/blob/4c4a968c287995c013c0ca8a383fce34bb22e0b9/lib/bunny/session.rb#L774

```
     RuntimeError:
       can't modify frozen Array
     # /Users/mattias/.gem/ruby/2.2.4/gems/bunny-2.5.1/lib/bunny/session.rb:774:in `map!'
     # /Users/mattias/.gem/ruby/2.2.4/gems/bunny-2.5.1/lib/bunny/session.rb:774:in `addresses_from'
     # /Users/mattias/.gem/ruby/2.2.4/gems/bunny-2.5.1/lib/bunny/session.rb:148:in `initialize'
     # /Users/mattias/.gem/ruby/2.2.4/gems/bunny-2.5.1/lib/bunny.rb:66:in `new'
     # /Users/mattias/.gem/ruby/2.2.4/gems/bunny-2.5.1/lib/bunny.rb:66:in `new'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/session.rb:20:in `create_connection'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/session.rb:14:in `initialize'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/connection.rb:20:in `new'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/connection.rb:20:in `block in instance'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/connection.rb:18:in `synchronize'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/connection.rb:18:in `instance'
     # /Users/mattias/.gem/ruby/2.2.4/bundler/gems/twingly-amqp-fd728d68cd93/lib/twingly/amqp/queue_publisher.rb:11:in `initialize'
```

**Comment by roback** [comment]
Opened an issue at https://github.com/ruby-amqp/bunny/issues/446
