### ISSUE TITLE
Undefined method `configuration' for Twingly::AMQP:Module (NoMethodError)

### ISSUE THREAD

**Issue by walro** [twingly/twingly-amqp#59]
When trying this out in of our projects I ran into the problem in the title.

```
2016-11-16T16:26:41.477975+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/twingly-amqp-4.2.0/lib/twingly/amqp/connection.rb:24:in `block in instance': undefined method `configuration' for Twingly::AMQP:Module (NoMethodError)
2016-11-16T16:26:41.477990+00:00 app[worker.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/twingly-amqp-4.2.0/lib/twingly/amqp/connection.rb:22:in `synchronize'
2016-11-16T16:26:41.477990+00:00 app[worker.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/twingly-amqp-4.2.0/lib/twingly/amqp/connection.rb:22:in `instance'
2016-11-16T16:26:41.477991+00:00 app[worker.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/twingly-amqp-4.2.0/lib/twingly/amqp/pinger.rb:11:in `initialize'
2016-11-16T16:26:41.477991+00:00 app[worker.1]: 	from /app/lib/bing_provider.rb:12:in `new'
2016-11-16T16:26:41.477992+00:00 app[worker.1]: 	from /app/lib/bing_provider.rb:12:in `initialize'
2016-11-16T16:26:41.477992+00:00 app[worker.1]: 	from bing-provider.rb:9:in `new'
2016-11-16T16:26:41.477993+00:00 app[worker.1]: 	from bing-provider.rb:9:in `block in <main>'
2016-11-16T16:26:41.477993+00:00 app[worker.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/sentry-raven-1.2.2/lib/raven/instance.rb:103:in `capture'
2016-11-16T16:26:41.477994+00:00 app[worker.1]: 	from bing-provider.rb:8:in `<main>'
```

Not sure why this happens as we use the `instance` method in the tests too, will investigate tomorrow.

**Comment by walro** [comment]
I yanked 4.2.0 from RubyGems until this is fixed. Will release as 4.2.1.

I think the problem is that we are missing requires.
